### PR TITLE
Email review

### PR DESCRIPTION
**Pull request by vbjeronimo**
- Added reviewMail() function. *
- Added removeMailToSend() function.**
- Added changes to compose.html to both accounts
- Cleaned the code a little bit.

*reviewMail() saves the email from compose.html to the local storage and if the user confirms that he wants to send the email, it will then be sent. After sending the email, it is erased from its specific item from local storage.

**removeMailToSend() erases the specific item that holds temporarily the email that will be sent and closes the window.

### CODE REVIEW

**Comment by just1ngray** [comment]
This doesn't seem done? There is no way to send emails? I don't think we should implement this into the master branch as it is unfinished.

There is no point to changing the io.js#write function? I don't understand the benefit, could you please tell me!

Take a look at the emailReview2 branch. You could add the questions right onto the page and it is currently working (except for being behind in the master's most recent fix to admin sent mail deletion).

**Comment by vbjeronimo** [comment]
But the send function is working on my version. The only issue is that I haven't found a way to return to the Inbox after the email is sent, but it is indeed working. But I'll try to work on your code and implement it there.

Also, I thought that changing io.js would make the code slightly easier to write. The only modification that I've done is that we wouldn't need to write JSON.stringify(var) when calling write(). But it's ok not to push this change.

I'll take a look at your branch and see what I can do.

**Comment by vbjeronimo** [comment]
Well, everything is already done, so I think we can merge your branch with master and I'll try to find something else to work on.

**Comment by just1ngray** [comment]
I liked your solution though! Mine wasn't as slick at all... despite looking I haven't been able to find any way to change the window location of a different window.

**Pull request closed without merging**
